image: Visual Studio 2019
skip_commits:
  message: /doco|Merge pull request.*/
install:
  - ps: choco install dotnetcore-sdk --no-progress --confirm --version 3.1.200
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore --filter Category!=Integration
test: off
artifacts: